<?php

namespace BusinessMag\MagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionnelRepository extends EntityRepository
{

	public function findProfess(){
	
    	$now =date('Y-m-d H:i:s');
		$qb=$this->createQueryBuilder('a');
		      $qb->where('a.published = :pub')
		         ->andWhere('a.dateDebut <= :now')
		         ->andWhere('a.dateFin >= :now')
		         //->orderBy('a.createdAt','desc')
		         //->setMaxResults(4)
		         ->setParameter('pub',1)
		         ->setParameter('now',$now);
		    return $qb->getQuery()->getResult();
	}
}
