<?php

namespace BusinessMag\MagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TexteDescriptifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexteDescriptifRepository extends EntityRepository
{
}
